"""my first migration

Revision ID: 1a77da3f38ac
Revises: 7ff7c002907b
Create Date: 2021-08-03 13:23:42.611089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a77da3f38ac'
down_revision = '7ff7c002907b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chat_name', table_name='chat')
    op.drop_index('ix_chat_hash_key', table_name='chat')
    op.create_index(op.f('ix_chat_hash_key'), 'chat', ['hash_key'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_hash_key'), table_name='chat')
    op.create_index('ix_chat_hash_key', 'chat', ['hash_key'], unique=False)
    op.create_index('ix_chat_name', 'chat', ['name'], unique=False)
    # ### end Alembic commands ###
