"""empty message

Revision ID: 7ff7c002907b
Revises: 35999bb84da5
Create Date: 2021-07-28 19:21:49.034806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ff7c002907b'
down_revision = '35999bb84da5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('name', sa.String(length=64), nullable=True))
    op.add_column('chat', sa.Column('hash_key', sa.String(length=24), nullable=True))
    op.create_index(op.f('ix_chat_hash_key'), 'chat', ['hash_key'], unique=True)
    op.create_index(op.f('ix_chat_name'), 'chat', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_name'), table_name='chat')
    op.drop_index(op.f('ix_chat_hash_key'), table_name='chat')
    op.drop_column('chat', 'hash_key')
    op.drop_column('chat', 'name')
    # ### end Alembic commands ###
